### ISSUE TITLE
Generic connection-string parser

### ISSUE THREAD

**Issue by vitaly-t** [FJSolutions/mongodb-uri#1]
In case you might find it interesting, there is generic [connection-string], which would let you avoid doing any parsing, so you can simplify your code a lot.

And if you have any questions -  just ask me ;)

[connection-string]:https://github.com/vitaly-t/connection-string

**Comment by FJSolutions** [comment]
Thanks for the interest, and your generic connection-string project looks really interesting. As with many projects, some of the gold only appears when the raw material goes into the fire. I will certainly be looking at this as an alternative parsing option.
